---
title: "Table 2 - Consumption Assets"
output: word_document
date: '2022-03-16'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE, echo=FALSE}
library(tidyverse)
library(parallel)
library(cmdstanr)
library(brms)
library(rstan)
library(posterior)
#library(magrittr)
library(knitr)
library(broom)
library(broom.mixed)
library(tidybayes)
library(bayesplot)
library(bayestestR)
library(kableExtra)
library(xtable)
library(sjPlot)
#library(texreg)
library(tidymodels)
library(estimatr)
library(Hmisc)
library(vip)
library(car)
library(sandwich)
```

Load the **consumption assets** model variables

```{r, include=FALSE}
# run linear model again using the bayesian "brms" package
consumption_assets_data <- read_csv("gik_hh_main.csv") %>%
  select(hhid, round, vid, block, eligible, samp_wgt, cost_deviation,
         treat_any, treat_GK, # treatment dummies
         assetsconsumption_asinh, # Outcome variable
         assetsconsumption_asinh_R1, # Baseline value of assetsconsumption_asinh, present in both rounds
         Lhh_wealth_asinh, Lvill_eligible_ratio, Lroomsnumb, Ldurablesexpenditure,  # controls
         Ldietarydi_x_Lassetscon, Lproductiv_x_Lassetscon) # Interactions
```

**consumption assets**: This is the basic benchmarking model utilizing the default, uninformed priors

```{r}
consumption_assets_bayesmodel <-
  brm(formula = assetsconsumption_asinh | weights(samp_wgt) ~
        cost_deviation + treat_any + treat_GK +
        assetsconsumption_asinh_R1 + Lhh_wealth_asinh + Lvill_eligible_ratio + Lroomsnumb + Ldurablesexpenditure +
        Ldietarydi_x_Lassetscon + Lproductiv_x_Lassetscon +
        (1 | block) + (1 | vid),
     data = consumption_assets_data,
     family = gaussian("identity"),
     seed = 1272022,
     warmup = 1000,
     iter = 2000,
     thin = 1,
     control = list(adapt_delta = .95, max_treedepth = 10),
     #backend = "cmdstanr",
     cores = 4, #overrides default 1 core
     #threads = 3,need to get cmdstanr package working here
     save_pars = save_pars(all = TRUE), # potentially allows for more post-processing functionality
     file = "uninformed_prior_outcomes\\consumption_assets_bayes")
```

```{r, include=FALSE, echo=FALSE}
tidy_consumption_assets_bayesmodel <- tidy(consumption_assets_bayesmodel)
#view(tidy_consumption_assets_bayesmodel)
write_csv(tidy_consumption_assets_bayesmodel, "uninformed_prior_outcomes\\consumption_assets_bayes.csv")
```

Model Summery
```{r}
summary(consumption_assets_bayesmodel)
```

Prior summery - how informative are priors
```{r}
prior_summary(consumption_assets_bayesmodel)
check_prior(consumption_assets_bayesmodel)
```

Diagnostics
```{r}
# trace diagnostic plot
mcmc_trace(consumption_assets_bayesmodel, n_warmup = 0,
           pars = c("b_Intercept", "b_cost_deviation", "b_treat_any", "b_treat_GK",
                    "b_assetsconsumption_asinh_R1", "b_Lhh_wealth_asinh", "b_Lvill_eligible_ratio", 
                    "b_Lroomsnumb", "b_Ldurablesexpenditure",
                    "b_Ldietarydi_x_Lassetscon", "b_Lproductiv_x_Lassetscon",
                    "sd_block__Intercept", "sd_vid__Intercept", "sigma"))
ggsave("table_2_diagnostics\\consumption_assets_trace.png", plot = last_plot(), width = 12, height = 5)

#density diagnostic plots
mcmc_dens(consumption_assets_bayesmodel,
           pars = c("b_Intercept", "b_cost_deviation", "b_treat_any", "b_treat_GK",
                    "b_assetsconsumption_asinh_R1", "b_Lhh_wealth_asinh", "b_Lvill_eligible_ratio", 
                    "b_Lroomsnumb", "b_Ldurablesexpenditure",
                    "b_Ldietarydi_x_Lassetscon", "b_Lproductiv_x_Lassetscon",
                    "sd_block__Intercept", "sd_vid__Intercept", "sigma"))
ggsave("table_2_diagnostics\\consumption_assets_dens.png", plot = last_plot(), width = 12, height = 5)

mcmc_dens_overlay(consumption_assets_bayesmodel,
           pars = c("b_Intercept", "b_cost_deviation", "b_treat_any", "b_treat_GK",
                    "b_assetsconsumption_asinh_R1", "b_Lhh_wealth_asinh", "b_Lvill_eligible_ratio", 
                    "b_Lroomsnumb", "b_Ldurablesexpenditure",
                    "b_Ldietarydi_x_Lassetscon", "b_Lproductiv_x_Lassetscon",
                    "sd_block__Intercept", "sd_vid__Intercept", "sigma"))
ggsave("table_2_diagnostics\\consumption_assets_dens_overlay.png", plot = last_plot(), width = 12, height = 5)

#acf (auto-correlation) diagnostic plot
mcmc_acf(consumption_assets_bayesmodel,
           pars = c("b_Intercept", "b_cost_deviation", "b_treat_any", "b_treat_GK",
                    "b_assetsconsumption_asinh_R1", "b_Lhh_wealth_asinh", "b_Lvill_eligible_ratio", 
                    "b_Lroomsnumb", "b_Ldurablesexpenditure",
                    "b_Ldietarydi_x_Lassetscon", "b_Lproductiv_x_Lassetscon",
                    "sd_block__Intercept", "sd_vid__Intercept", "sigma"))
ggsave("table_2_diagnostics\\consumption_assets_assets_acf.png", plot = last_plot(), width = 12, height = 5)
```

posterior predictive checks
```{r}
pp_check(consumption_assets_bayesmodel, ndraws = 100)
pp_check(consumption_assets_bayesmodel, ndraws = 10, type = 'error_scatter_avg', alpha = .1)
```
